name: API Test with Allure

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install & Test
      run: |
        pip install -r requirements.txt
        pytest test_api_ok.py -v --alluredir=reports --clean-alluredir

    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: reports

    - name: Allure Report  # 生成美报告
      if: always()
      uses: simple-elf/allure-report-action@v1
      with:
        allure_results: allure-results
      id: allure-report

    - name: View Allure Report  # 网页评论
      if: always()
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data } = await github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: '## [Allure报告] ${{ steps.allure-report.outputs.report_url }}'
          })